const fs = require('fs');
const path = require('path');

const baseUrl = 'https://azhai-six.vercel.app';
const today = new Date().toISOString().slice(0, 10);

const tools = [
  'word-counter','char-counter','sentence-counter','paragraph-counter','word-frequency',
  'case-converter','remove-spaces','find-replace','line-sorter','alpha-sorter',
  'text-reverser','duplicate-remover','lorem-generator','slug-generator',
  'keyword-density','keyword-extract','meta-gen','meta-desc-gen','og-generator',
  'canonical-gen','robots-txt','sitemap-gen',
  'json-formatter','json-validator','xml-formatter','xml-validator',
  'markdown-editor','markdown-preview','html-previewer','regex-tester',
  'url-encoder','url-decoder','html-encoder','html-decoder',
  'b64-encoder','b64-decoder','hash-generator',
  'hreflang-gen','schema-gen','faq-schema-gen','article-schema-gen','breadcrumb-schema-gen'
];

// Blog posts from build-blog.js
const blogs = [
  'ultimate-guide-seo-text-tools',
  'how-to-write-perfect-meta-descriptions',
  'json-formatting-best-practices',
  'markdown-for-bloggers',
  'understanding-canonical-tags-seo',
  'open-graph-tags-social-media',
  'google-ai-overview-spam-policy-2026',
  'optimize-google-ai-overviews',
  'google-june-2026-spam-update',
  'ai-content-detection-2026',
  'query-fanout-seo-2026',
  'how-to-get-cited-google-ai-overviews'
];

// Standalone blog pages (not generated by build-blog.js)
const standaloneBlogs = ['eeat-2026-google-trust-guide'];

const staticPages = [
  {url: '/', priority: '1.0', changefreq: 'weekly'},
  {url: '/about.html', priority: '0.7', changefreq: 'monthly'},
  {url: '/contact.html', priority: '0.6', changefreq: 'monthly'},
  {url: '/advertise.html', priority: '0.6', changefreq: 'monthly'},
  {url: '/privacy-policy.html', priority: '0.5', changefreq: 'yearly'},
  {url: '/terms.html', priority: '0.5', changefreq: 'yearly'},
  {url: '/cookie-policy.html', priority: '0.5', changefreq: 'yearly'},
  {url: '/tools/', priority: '0.9', changefreq: 'weekly'},
  {url: '/tools/smart-text-lab.html', priority: '0.9', changefreq: 'monthly'},
  {url: '/blog/', priority: '0.9', changefreq: 'weekly'}
];

let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

// Static pages
staticPages.forEach(p => {
  xml += `  <url><loc>${baseUrl}${p.url}</loc><lastmod>${today}</lastmod><changefreq>${p.changefreq}</changefreq><priority>${p.priority}</priority></url>\n`;
});

// Tool pages
tools.forEach(tool => {
  xml += `  <url><loc>${baseUrl}/tools/${tool}.html</loc><lastmod>${today}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>\n`;
});

// Blog pages
blogs.forEach(blog => {
  xml += `  <url><loc>${baseUrl}/blog/${blog}.html</loc><lastmod>${today}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>\n`;
});

// Standalone blog pages
standaloneBlogs.forEach(blog => {
  xml += `  <url><loc>${baseUrl}/blog/${blog}.html</loc><lastmod>${today}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>\n`;
});

xml += '</urlset>';

const outPath = path.join(__dirname, 'public', 'sitemap.xml');
fs.mkdirSync(path.dirname(outPath), {recursive: true});
fs.writeFileSync(outPath, xml, 'utf8');
console.log('Sitemap generated: ' + outPath);
console.log('Total URLs: ' + (staticPages.length + tools.length + blogs.length + standaloneBlogs.length));
