const fs = require('fs');
let c = fs.readFileSync('build-blog.js', 'utf8');

// Add new posts to the posts array
const newPosts = `{slug:'how-to-create-robots-txt-file',title:'How to Create a Robots.txt File: Complete Step-by-Step Guide',desc:'Learn how to create a robots.txt file that tells search engines which pages to crawl and which to skip. Free generator tool included.',category:'Technical SEO',date:'2026-07-08',readTime:'9 min',image:'/blog/images/robots-txt-guide-banner.svg'},
{slug:'xml-sitemap-guide-seo',title:'XML Sitemap Guide: How to Create and Submit Your Sitemap for SEO',desc:'An XML sitemap helps search engines discover and index your pages faster. Learn how to create, optimize, and submit your sitemap to Google.',category:'Technical SEO',date:'2026-07-08',readTime:'10 min',image:'/blog/images/xml-sitemap-guide-banner.svg'}`;

c = c.replace(
  "{slug:'how-to-write-meta-descriptions',title:'How to Write Meta Descriptions That Get Clicks in 2026',desc:'Meta descriptions impact CTR more than rankings. Learn how to write compelling meta descriptions that attract clicks and improve your search visibility.',category:'SEO Tutorial',date:'2026-07-06',readTime:'7 min',image:'/blog/images/write-meta-descriptions-banner.svg'}\n];",
  "{slug:'how-to-write-meta-descriptions',title:'How to Write Meta Descriptions That Get Clicks in 2026',desc:'Meta descriptions impact CTR more than rankings. Learn how to write compelling meta descriptions that attract clicks and improve your search visibility.',category:'SEO Tutorial',date:'2026-07-06',readTime:'7 min',image:'/blog/images/write-meta-descriptions-banner.svg'},\n" + newPosts + "\n];"
);

// Add new blog contents
const robotsContent = '<h2>What Is a Robots.txt File?</h2><p>A robots.txt file is a plain text file at the root of your website that tells search engine crawlers which pages to access and which to skip. It is the first file Googlebot reads when it visits your site.</p><h2>Why Robots.txt Matters for SEO</h2><p>Search engines have a crawl budget. If crawlers waste time on low-value pages, your important pages may not get crawled as often.</p><p>A proper robots.txt file prevents crawl budget waste, protects sensitive areas, and guides crawlers toward your highest-priority pages.</p><h2>Robots.txt Syntax Explained</h2><p><strong>User-agent:</strong> Which crawler the rules apply to. Use * for all crawlers.</p><p><strong>Disallow:</strong> URLs crawlers cannot access. Disallow: /admin/ blocks everything under /admin/.</p><p><strong>Allow:</strong> Overrides a Disallow rule for a specific path.</p><p><strong>Sitemap:</strong> Points crawlers to your XML sitemap.</p><h2>Common Robots.txt Mistakes</h2><p><strong>Mistake 1: Blocking CSS and JavaScript.</strong> Google needs to render your pages to understand them.</p><p><strong>Mistake 2: Using robots.txt to remove pages from indexing.</strong> Robots.txt prevents crawling, not indexing. Use noindex meta tags instead.</p><p><strong>Mistake 3: Forgetting the Sitemap directive.</strong> Always include Sitemap in your robots.txt.</p><h2>Step-by-Step: Create Your Robots.txt File</h2><p><strong>Step 1: Plan Your Rules.</strong> Decide which areas should be crawled and which should not.</p><p><strong>Step 2: Write the File.</strong> Start with User-agent, add Disallow and Allow directives, end with Sitemap.</p><p><strong>Step 3: Test Your Rules.</strong> Use Google Search Console Robots.txt Tester to verify.</p><p><strong>Step 4: Upload to Root Directory.</strong> Place at yourdomain.com/robots.txt.</p><p><strong>Step 5: Submit to Search Engines.</strong> Submit your robots.txt URL in Google Search Console.</p><h2>Generate Your Robots.txt File</h2><p>Our free <a href="/tools/robots-txt.html">Robots.txt Generator</a> creates a complete robots.txt file in seconds.</p>';

const sitemapContent = '<h2>What Is an XML Sitemap?</h2><p>An XML sitemap is a file that lists all the important pages on your website in a format search engines can read. It acts as a roadmap for Googlebot, helping crawlers discover and index your content efficiently.</p><h2>Why XML Sitemaps Matter for SEO</h2><p>Google does not guarantee it will crawl every page on your site. Without a sitemap, crawlers rely on internal links. An XML sitemap explicitly tells Google which pages exist and which matter most.</p><p>Sites that submit XML sitemaps typically see 15-25% faster indexing of new pages.</p><h2>XML Sitemap Structure</h2><p><strong>&lt;urlset&gt;</strong> — Container element defining the sitemap protocol version.</p><p><strong>&lt;url&gt;</strong> — Each page gets its own URL entry.</p><p><strong>&lt;loc&gt;</strong> — The full URL. Use absolute URLs.</p><p><strong>&lt;lastmod&gt;</strong> — Date last modified in ISO 8601 format.</p><p><strong>&lt;changefreq&gt;</strong> — How often the page changes.</p><p><strong>&lt;priority&gt;</strong> — Importance relative to other pages (0.0 to 1.0).</p><h2>What to Include</h2><p>Include: homepage, category pages, product pages, blog posts, landing pages.</p><p>Exclude: tag pages, author pages, thin content, duplicate pages, noindex pages.</p><h2>Sitemap Best Practices</h2><p><strong>Keep under 50,000 URLs.</strong> Google limit is 50,000 URLs or 50MB uncompressed.</p><p><strong>Use absolute URLs.</strong> Always include protocol and domain.</p><p><strong>Update lastmod dates.</strong> Only when content actually changes.</p><p><strong>Include in robots.txt.</strong> Add Sitemap directive.</p><p><strong>Submit to Google Search Console.</strong> Accelerates discovery.</p><h2>Common Sitemap Mistakes</h2><p><strong>Mistake 1: Including noindex pages.</strong> Do not include pages with noindex tags.</p><p><strong>Mistake 2: Never updating.</strong> Use a dynamic generator that updates automatically.</p><p><strong>Mistake 3: Broken URLs.</strong> Every URL should return 200 status code.</p><h2>Generate Your XML Sitemap</h2><p>Our free <a href="/tools/sitemap-gen.html">XML Sitemap Generator</a> creates a complete sitemap in seconds.</p>';

c = c.replace(
  "blogContents['query-fanout-seo-2026'] = '",
  "blogContents['how-to-create-robots-txt-file'] = '" + robotsContent.replace(/'/g, "\\'") + "';\n\nblogContents['xml-sitemap-guide-seo'] = '" + sitemapContent.replace(/'/g, "\\'") + "';\n\nblogContents['query-fanout-seo-2026'] = '"
);

fs.writeFileSync('build-blog.js', c, 'utf8');
console.log('Done - added 2 new blog posts');
